# Generated by Django 5.2 on 2025-05-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
