# Generated by Django 5.2 on 2025-05-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
