# Generated by Django 5.2 on 2025-05-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
