# Generated by Django 5.2 on 2025-05-19 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_description', models.TextField()),
                ('store_name', models.CharField(max_length=100)),
                ('bank_details', models.TextField()),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='vendors/')),
                ('created_at', models.DateTimeField()),
                ('contact_details', models.TextField()),
                ('shipping_policy', models.TextField()),
                ('refund_policy', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
